# Generated by Django 4.0 on 2022-01-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.IntegerField(unique=True)),
                ('CourseName', models.CharField(max_length=150)),
                ('CourseInstructor', models.CharField(max_length=150)),
                ('CreditHours', models.IntegerField()),
                ('RequiredCourse', models.CharField(max_length=150)),
                ('CourseCode', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=150)),
                ('ID', models.IntegerField(unique=True)),
                ('MobNumber', models.IntegerField()),
                ('Email', models.CharField(max_length=300)),
                ('Birthday', models.IntegerField()),
                ('Gender', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=200)),
                ('ID', models.IntegerField(unique=True)),
                ('MobNumber', models.IntegerField()),
                ('Email', models.CharField(max_length=200)),
                ('Birthday', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
    ]
